### ISSUE TITLE
Add a "flow" heading to the README

### ISSUE THREAD

**Issue by stevemar** [asurve/SystemML_Demo#12]
A journey should have a "flow" section that explains your architecture diagram. See https://github.com/IBM/elasticsearch-spark-recommender#flow as an example. cc @rhagarty

**Comment by asurve** [comment]
Diagram shown in SystemML Usage journey is to show SystemML as a "State of the art". 
Flow section is not applicable for this diagram.
I don't think we need to have "Flow" section for every ReadMe file it depends on context.

Probably some text needs to be added to explain this diagram in ReadMe file which I will add.

**Comment by stevemar** [comment]
OK, i created a PR (https://github.com/IBM/SystemML_Usage/pull/13) to rename the previous diagram to 'state of the art', it still needs some explanatory text. 

In the same PR i created a new architecture diagram that explains the user's flow when going through the journey. This is a requirement for all journeys, all published journeys have one.
