### ISSUE TITLE
Editing the README

### ISSUE THREAD

**Issue by MadisonJMyers** [asurve/SystemML_Demo#8]
Arvind this looks great! The steps are clear and will definitely help people get up and running with SystemML on DSX. As requested I do have some minor edits. I go in order so you can edit along with my notes. Please see below:

- Title is unclear: perhaps “Using SystemML in the Data Science Experience (DSX) for your Machine Learning Project” or “Using SystemML for Machine Learning Problems in a Data Science Experience (DSX) Notebook” or just simply "Getting started with SystemML in a Data Science Experience (DSX) Notebook"
- In the first paragraph where you write “In this developer journey….” I’d love to see you briefly introduce SystemML like you did with DSX. It would be best to do this before you introduce DSX to stay consistent with the order you presented it in the sentence. However because you go on to use SystemML second, it would be best to consistently have this mentioned after DSX. Up to you.
- “When the reader has completed this journey, they will understand how to:” should be “When you finish this journey, you will understand how to:”
- “The intended audience for this journey is application developers” should be “The intended audience for this journey is both application developers”…
- “In this case” should be something similar to “Specifically,”
- “In this case, a Linear Regression example is provided to demonstrate the ease and power of Apache SystemML. There are various out of box algorithms provided by Apache SystemML.” Should be combined to be like: “Specifically, a Linear Regression example is provided to demonstrate the ease and power of Apache SystemML, although there are various other algorithms provided by Apache SystemML that the user can use on their own problems.”
- Then I’d open the next sentence with “Additionally, users can develop”…
- “roadmap” should be “the roadmap”
- Add a period at the end of that sentence and the website. “…please visit the Apache SystemML website.”
- At your bullet point under Featured Technologies, “Apache SystemML” should have a colon after (“Apache SystemML:”)
- I know that the journey team prefers smaller headers so for “Included Components”, “Watch the Video”, “Steps” and “License” you will probably be asked to make them one level smaller. You should probably go ahead and do this for efficiency. 
- For number 4 in the listed steps that are highlighted, “4. Save and Share” should be “4. Save and share” for consistency with uppercase.
- Under the expanded step “1. Sign up for the Data Science Experience” sentence two needs changed from “By signing up for the Data Science Experience, two services: DSX-Spark and DSX-ObjectStore will be created in your Bluemix account.” to “By signing up for the Data Science Experience, two services will be created in your Bluemix account: DSX-Spark and DSX-ObjectStore.”
- “Login to your Bluemix account” should be “Login or create your Bluemix account” in case they do not have one.
- “ If not already used, name your service DSX-Spark.” should be “If the name has not already been used, name your service DSX-Spark so that you can keep track of it.” Or you can just say that the user can leave the defaults.
- Same with the Object Storage line.
- I like your clear explanation in Step 3!
- In step 3 in the first 3 bullet points “this” should be changed to “which”. Just my preference.
- For consistency you may want to add a period at the end of each bullet point, because it is inconsistent throughout the README, but that is just my preference.
- Awesome job! This will be a great journey!

**Comment by rhagarty** [comment]
Thanks for the great input @MadisonJMyers.  Please take a look at my PR.

Also, @asurve - please verify all changes.

**Comment by MadisonJMyers** [comment]
Just reviewed! LGTM. Thanks @rhagarty!
