### ISSUE TITLE
Editing the Notebook

### ISSUE THREAD

**Issue by MadisonJMyers** [asurve/SystemML_Demo#9]
As requested, I've also edited your notebook. While I think this will be an awesome journey, there are definitely some edits you should make to make it a bit clearer for the user/reader. I'm excited to see the final product! See my edits below:

- This isn’t a requirement, but I would add period after each bold point. For example the first one is: “ Machine learning library for scalable distributable solution”. This is just my preference though.
- “Future SystemML developments” is a little confusing. Maybe say something like, “In the future, SystemML plans to release developments that include…”
- Because you are starting a new paragraph, “It contains many popular machine learning algorithms” should be specific. Instead, write “Currently, SystemML contains many popular machine learning algorithms”…
- “However, an algorithm migrated to run on a large scale environment may not produce the same expected results due to problems in original algorithm or errors in converting the algorithm to run on a cluster.” should be “However, an algorithm migrated to run on a large scale environment may not produce the same expected results due to unforeseen problems in the original algorithm or errors in converting the algorithm to run on a cluster.”
- “Revising the algorithm ends up being an error-prone, time-consuming process since the Systems Engineer doesn't have expertise with the algorithm and the Data Scientist isn't familiar with distributed programming.” should be clearer by adding “In this situation, revising the algorithm ends up being an error-prone, time-consuming process as the Systems Engineer doesn't usually have expertise with the algorithm and the Data Scientist isn't familiar with the distributed programming that Systems Engineers implement.”
- “A Data Scientist can focus on algorithm development and let Apache SystemML distribute processing as needed when that same algorithm is run with bigger data on larger environment.” would be clearer as: “With SystemML, a Data Scientist can focus on algorithm development and let Apache SystemML take care of the distributive processing as needed when running with bigger data in a larger environment.”
- Under matrix multiplication, “There are multiple libraries available for Matrix operations.” should be “In SystemML, there are multiple libraries available for Matrix operations.”
- “Following code snippet shows numpy used to do matrix multiplication of transpose of matrix to itself of matrix size (1M x 1K). ” should be “The following code snippet shows numpy being used to do a matrix multiplication.“ (I removed the last part because it is unclear and redundant (1M x 1K is in the title).)
- “As data can fit into memory, you get a result.” Is very confusing. Not sure what you mean here. You can probably remove it. Or rephrase. I’m happy to review how you change it.
- “Following code snippet shows numpy used to do matrix multiplication of transpose of matrix to itself of matrix size (10M x 1K). As data cannot fit into memory, operation gives an error.” is also unclear. Perhaps change it to “The following code snippet shows numpy being used to do a matrix multiplication, this time with a matrix size 10M x 1K. This time, the data cannot fit into memory, so the operation gives an error.”
- “Following code snippet shows matrix multiplication of transpose of matrix to itself of matrix size (10M x 1K). Apache SystemML does not depend just on local memory but it leverages cluster environment to do any operation. An operation with same data size which cannot be run using Numpy can be done using Apache SystemML as it performs operations in distributed environment if data cannot fit onto local memory. It also demonstrates use of Apache SystemML's MLContext Application Programming Interface (API) to execute the program.” would be clearer as: “The following code snippet shows a matrix multiplication with a matrix size 10M x 1K. This demonstrates that Apache SystemML does not depend just on local memory, but instead leverages the cluster environment to do any operation. This means that a similar operation with the same data size, which cannot be run using numpy, can be done using Apache SystemML. This example also demonstrates the use of Apache SystemML's MLContext Application Programming Interface (API).”
- Under “Data generation”, “Lets generate some synthetic data through script specified below and run through Apache SystemML. We will use same data for all use cases described in the notebook below.” should be: “Now let’s generate some synthetic data through a script specified below and run through Apache SystemML. We will use the same data for all use cases described in the notebook below.”
- The “Linear regression direct solve” is unclear. Perhaps name it simply “Linear Regression”?
- “Linear regression “out-of-the-box”” should be “Use a pre-coded linear regression algorithm” or something similar that is clearer. At the least just switch it around to be ““Out-of-the-box” linear regression”
- (This comment pertains to the above two comments as well ^.) Perhaps to make the headers consistent you could add a colon. Specifically what I’m saying is either reword all of the titles to make them clearer (especially the linear regression headers) or do something like this: “Linear Regression: batch gradient descent”. As shown, I’d also capitalize the r. Implement on all of these headers.
- Under that header change “one takes” to “you can take”. I believe the journey team wants that form throughout all journeys.
- “A problem with gradient descent is that it takes very similar directions many times. Modifying the original gradient descent algorithm with an additional step to enforcing conjugacy resolves this issue.” is very confusing. Try rewording.
- Exciting! This journey will be very helpful once it moves forward!

**Comment by xwu0226** [comment]
@MadisonJMyers I see review comments are merged. Can you check and close the issue? Thanks!

**Comment by MadisonJMyers** [comment]
A few minor things left if you have time @asurve. See below:

 - Make sure your title is capitalized (machine learning should be Machine Learning)
 - "Machine learning library for scalable distributable solution: should be "a scalable..." or plural "solutions"
 
Otherwise it LGTM!
